version: "3"

services:

  mariadb:
    image: mariadb
    container_name: db01
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./provisioning/resources/sql:/docker-entrypoint-initdb.d
    healthcheck:
        test: "exit 0"
    networks:
      quote_network:
        ipv4_address: 192.168.56.15
        

  memcached:
    image: memcached
    container_name: mc01
    networks:
      quote_network:
        ipv4_address: 192.168.56.14

  app:
    build:
      context: .
      dockerfile: ./provisioning/resources/django/Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
      memcached:
        condition: service_started
    
    
  django1:
    extends:
      service: app
    container_name: dj01
    extra_hosts:
      - "db01:192.168.56.15"
      - "mc01:192.168.56.14"
    depends_on: 
      - app
    networks:
      quote_network:
        ipv4_address: 192.168.56.16

  django2:
    extends:
      service: app
    container_name: dj02
    extra_hosts:
      - "db01:192.168.56.15"
      - "mc01:192.168.56.14"
    depends_on: 
      - app
    networks:
      quote_network:
        ipv4_address: 192.168.56.17

  nginx:
    image: nginx
    container_name: ngx01
    extra_hosts:
      - "dj01:192.168.56.16"
      - "dj02:192.168.56.17"
    volumes:
      - ./provisioning/resources/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django1
      - django2
        
    networks:
      quote_network:
        ipv4_address: 192.168.56.10

  
        

networks:
  quote_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24