version: "3"

services:
  mariadb:
    image: mariadb
    container_name: db01
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./provisioning/resources/sql:/docker-entrypoint-initdb.d
    networks:
      quote_network:
        ipv4_address: 192.168.56.15

  memcached:
    image: memcached
    container_name: mc01
    networks:
      quote_network:
        ipv4_address: 192.168.56.14



networks:
  quote_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24